name = "firstmover-cron"
main = "worker.js"
compatibility_date = "2024-04-12"

[triggers]
crons = ["*/2 * * * *"] # Every 2 minutes

[observability]
enabled = true

[vars]
# Optional default vars, NOT for secrets

